apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
    - image: back-frontend:latest
      imagePullPolicy: Never
      name: frontend-app
      ports:
        - containerPort: 4200
          protocol: TCP
  restartPolicy: OnFailure
