apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: pokemon-service
  name: pokemon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pokemon-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: pokemon-service
    spec:
      containers:
        - env:
            - name: PYTHONUNBUFFERED
              value: "1"
          image: back-pokemon-service:latest
          imagePullPolicy: Never
          name: pokemon-service
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
